service_django/application/src/home/module/documentation/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

urlpatterns = [
    url(r'^documentation/', include('src.home.module.documentation.documentation.urls', namespace='documentation')),
]

service_django/application/src/home/module/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

urlpatterns = [
    url(r'^website/', include('src.home.module.home.website.urls', namespace='website')),
]

service_django/application/src/home/module/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

urlpatterns = [
    url(r'^home/', include('src.home.module.home.urls', namespace='home')),
    url(r'^documentation/', include('src.home.module.documentation.urls', namespace='documentation')),
]

service_django/application/src/home/urls.py
# -*- coding: utf-8 -*-
from . import views
from django.conf.urls import include, url

urlpatterns = [
    url(regex=r'^$', view=views.index, name='index'),
    url(regex=r'^title/$', view=views.title, name='title'),
    url(regex=r'^div_load/$', view=views.div_load, name='div_load'),
    url(regex=r'^div_header/$', view=views.div_header, name='div_header'),
    url(regex=r'^div_leftside/$', view=views.div_leftside, name='div_leftside'),
    url(regex=r'^div_center_div_content/$', view=views.div_center_div_content, name='div_center_div_content'),
    url(regex=r'^div_center_div_footer/$', view=views.div_center_div_footer, name='div_center_div_footer'),
    #
    url(regex=r'^login/$', view=views.login, name='login'),
    url(regex=r'^login_forgot_credential_1/$', view=views.login_forgot_credential_1, name='login_forgot_credential_1'),
    url(regex=r'^login_forgot_credential_2/(?P<pk>\d+)/$', view=views.login_forgot_credential_2, name='login_forgot_credential_2'),
    url(regex=r'^login_forgot_credential_3/(?P<pk>\d+)/$', view=views.login_forgot_credential_3, name='login_forgot_credential_3'),
    url(regex=r'^login_request/$', view=views.login_request, name='login_request'),
    url(regex=r'^logout/$', view=views.logout, name='logout'),
    url(regex=r'^profile/$', view=views.profile, name='profile'),
    url(regex=r'^locale/$', view=views.locale, name='locale'),
    #
    url(r'^module/', include('src.home.module.urls', namespace='module')),
]

service_django/application/src/home/module/documentation/documentation/views.py
# -*- coding: utf-8 -*-
from .... import utils as home_utils
from src.documentation import models as documentation_models
from src.security import (
    decorators as security_decorators,
    utils as security_utils,
)
from django import http


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user(security_from_module=security_utils.SECURITY_FROM_MODULE_HOME)
def index(request):
    data = dict()
    data['BOOLEAN_ERROR'] = False
    data['HTML_DIV_CENTER_DIV_CONTENT'] = home_utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_center/div_content/documentation/documentation/div_content.html',
    )
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user(security_from_module=security_utils.SECURITY_FROM_MODULE_HOME)
def tree(request):
    data = dict()
    data['BOOLEAN_ERROR'] = False
    instances = documentation_models.Document.objects.all().filter(is_active=True)
    data['HTML_DIV_CENTER_DIV_CONTENT_DOCUMENTATION_DOCUMENTATION_TREE'] = home_utils.html_template(
        request=request,
        context={
            'ctx_instances': instances,
        },
        template='home/_include_/div_center/div_content/documentation/documentation/_include_/tree.html',
    )
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user(security_from_module=security_utils.SECURITY_FROM_MODULE_HOME)
def content(request, pk):
    data = dict()
    data['BOOLEAN_ERROR'] = False
    try:
        pk = int(pk)
    except ValueError:
        return home_utils.jsonresponse_error(request=request)
    if pk > 0:
        instance = documentation_models.Document.objects.instance___by_pk(pk=pk)
        if instance is None:
            return home_utils.jsonresponse_error(request=request)
        context = {
            'ctx_title': instance,
            'ctx_content': instance.string___content(),
        }
    else:
        instances = documentation_models.Document.objects.all().filter(is_active=True)
        if instances.count() > 0:
            instance = instances[0]
            context = {
                'ctx_title': instance,
                'ctx_content': instance.string___content(),
            }
        else:
            context = dict()
    data['HTML_DIV_CENTER_DIV_CONTENT_DOCUMENTATION_DOCUMENTATION_CONTENT'] = home_utils.html_template(
        request=request,
        context=context,
        template='home/_include_/div_center/div_content/documentation/documentation/_include_/content.html',
    )
    return http.JsonResponse(data)

service_django/application/src/home/module/home/website/views.py
# -*- coding: utf-8 -*-
from .... import utils as home_utils
from src.security import (
    decorators as security_decorators,
)
from django import http


@security_decorators.required_request_is_ajax()
def index(request):
    data = dict()
    data['BOOLEAN_ERROR'] = False
    data['HTML_DIV_CENTER_DIV_CONTENT'] = home_utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_center/div_content/home/website/div_content.html',
    )
    return http.JsonResponse(data)

service_django/application/src/home/views.py
# -*- coding: utf-8 -*-
from . import utils
from src.security import (
    decorators as security_decorators,
    utils as security_utils
)
from django import http, shortcuts


def index(request):
    context = dict()
    return shortcuts.render(
        request=request,
        context=context,
        template_name='home/application.html'
    )


@security_decorators.required_request_is_ajax()
def title(request):
    data = dict()
    data['HTML_TITLE'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/title/title.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def div_load(request):
    data = dict()
    data['HTML_DIV_LOAD'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_load/div_load.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def div_header(request):
    data = dict()
    data['HTML_DIV_HEADER'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_header/div_header.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def div_leftside(request):
    data = dict()
    data['HTML_DIV_LEFTSIDE'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_leftside/div_leftside.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def div_center_div_content(request):
    data = dict()
    data['HTML_DIV_CENTER_DIV_CONTENT'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_center/div_content/div_content.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def div_center_div_footer(request):
    data = dict()
    data['HTML_DIV_CENTER_DIV_FOOTER'] = utils.html_template(
        request=request,
        context=dict(),
        template='home/_include_/div_center/div_footer/div_footer.html'
    )
    data['BOOLEAN_ERROR'] = False
    return http.JsonResponse(data)


@security_decorators.required_request_is_ajax()
def login(request):
    return security_utils.jsonresponse_login(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )


@security_decorators.required_request_is_ajax()
def login_forgot_credential_1(request):
    return security_utils.jsonresponse_login_forgot_credential_1(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )


@security_decorators.required_request_is_ajax()
def login_forgot_credential_2(request, pk):
    return security_utils.jsonresponse_login_forgot_credential_2(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
def login_forgot_credential_3(request, pk):
    return security_utils.jsonresponse_login_forgot_credential_3(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
def login_request(request):
    return security_utils.jsonresponse_login_request(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user(security_from_module=security_utils.SECURITY_FROM_MODULE_HOME)
def logout(request):
    return security_utils.jsonresponse_logout(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user(security_from_module=security_utils.SECURITY_FROM_MODULE_HOME)
def profile(request):
    return security_utils.jsonresponse_profile(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )


@security_decorators.required_request_is_ajax()
def locale(request):
    return security_utils.jsonresponse_locale(
        request=request,
        security_from_module=security_utils.SECURITY_FROM_MODULE_HOME
    )

service_django/application/templates/home/application.html
{% spaceless %}
    {% load i18n static %}
    {% now "YmdHis" as ctx_now %}
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, user-scalable=no, shrink-to-fit=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0"/>
            <link href="{% static "_images_/favicon.png" %}?{{ ctx_now }}" rel="shortcut icon" type="image/png"/>
            <title data-url="{% url "home:title" %}">...</title>
            <link href="{% static "_vendors_/bootstrap/css/bootstrap.min.css" %}?{{ ctx_now }}" rel="stylesheet"/>
            <link href="{% static "_vendors_/font-awesome/css/font-awesome.min.css" %}?{{ ctx_now }}" rel="stylesheet"/>
            <link href="{% static "_vendors_/jquery-multiple-collapsible-tree-table/css/jquery.multiple.collapsible.tree.table.css" %}?{{ ctx_now }}" rel="stylesheet">
            <link href="{% static "home/dist/css/application.min.css" %}?{{ ctx_now }}" rel="stylesheet"/>
        </head>
        <body>
            <div id="div-load" data-url="{% url "home:div_load" %}"></div>
            <div id="div-header" data-url="{% url "home:div_header" %}"></div>
            <div id="div-leftside" data-url="{% url "home:div_leftside" %}"></div>
            <div id="div-center" class="d-flex flex-column justify-content-between">
                <div id="div-content" data-url="{% url "home:div_center_div_content" %}"><p class="m-0 p-0">&nbsp;</p></div>
                <div id="div-footer" class="d-flex flex-row justify-content-start" data-url="{% url "home:div_center_div_footer" %}"></div>
            </div>
            <div id="div-modal" class="modal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="true"></div>
            <div id="div-modal-modal" class="modal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="true"></div>
            <script src="{% static "_vendors_/jquery/js/jquery.min.js" %}?{{ ctx_now }}"></script>
            <script src="{% static "_vendors_/popper/js/popper.min.js" %}?{{ ctx_now }}"></script>
            <script src="{% static "_vendors_/bootstrap/js/bootstrap.min.js" %}?{{ ctx_now }}"></script>
            <script src="{% static "_vendors_/jquery-multiple-collapsible-tree-table/js/jquery.multiple.collapsible.tree.table.js" %}?{{ ctx_now }}"></script>
            <script src="{% static "home/dist/js/application.min.js" %}?{{ ctx_now }}"></script>
        </body>
    </html>
{% endspaceless %}