service_django/application/src/administration/module/security/group/urls.py
# -*- coding: utf-8 -*-
from . import views
from django.conf.urls import url

urlpatterns = [
    url(regex=r'^$', view=views.index, name='index'),
    url(regex=r'^table_tbody_and_pagination_reload/$', view=views.table_tbody_and_pagination_reload, name='table_tbody_and_pagination_reload'),
    url(regex=r'^table_tbody_and_pagination_tree_reload/$', view=views.table_tbody_and_pagination_tree_reload, name='table_tbody_and_pagination_tree_reload'),
    url(regex=r'^create/$', view=views.create, name='create'),
    url(regex=r'^detail/(?P<pk>\d+)/$', view=views.detail, name='detail'),
    url(regex=r'^update/(?P<pk>\d+)/$', view=views.update, name='update'),
    url(regex=r'^delete/(?P<pk>\d+)/$', view=views.delete, name='delete'),
]

service_django/application/src/administration/module/security/ldapuser/urls.py
# -*- coding: utf-8 -*-
from . import views
from django.conf.urls import url

urlpatterns = [
    url(regex=r'^$', view=views.index, name='index'),
    url(regex=r'^table_tbody_and_pagination_reload/$', view=views.table_tbody_and_pagination_reload, name='table_tbody_and_pagination_reload'),
    url(regex=r'^create/$', view=views.create, name='create'),
    url(regex=r'^detail/(?P<pk>\d+)/$', view=views.detail, name='detail'),
    url(regex=r'^update/(?P<pk>\d+)/$', view=views.update, name='update'),
    url(regex=r'^delete/(?P<pk>\d+)/$', view=views.delete, name='delete'),
]

service_django/application/src/administration/module/security/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

urlpatterns = [
    url(r'^requestedlocaluser/', include('src.administration.module.security.requestedlocaluser.urls', namespace='requestedlocaluser')),
    url(r'^localuser/', include('src.administration.module.security.localuser.urls', namespace='localuser')),
    url(r'^requestedldapuser/', include('src.administration.module.security.requestedldapuser.urls', namespace='requestedldapuser')),
    url(r'^ldapuser/', include('src.administration.module.security.ldapuser.urls', namespace='ldapuser')),
    url(r'^group/', include('src.administration.module.security.group.urls', namespace='group')),
    url(r'^permission/', include('src.administration.module.security.permission.urls', namespace='permission')),
]

service_django/application/src/home/module/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

urlpatterns = [
    url(r'^home/', include('src.home.module.home.urls', namespace='home')),
    url(r'^documentation/', include('src.home.module.documentation.urls', namespace='documentation')),
]

service_django/application/src/home/urls.py
# -*- coding: utf-8 -*-
from . import views
from django.conf.urls import include, url

urlpatterns = [
    url(regex=r'^$', view=views.index, name='index'),
    url(regex=r'^title/$', view=views.title, name='title'),
    url(regex=r'^div_load/$', view=views.div_load, name='div_load'),
    url(regex=r'^div_header/$', view=views.div_header, name='div_header'),
    url(regex=r'^div_leftside/$', view=views.div_leftside, name='div_leftside'),
    url(regex=r'^div_center_div_content/$', view=views.div_center_div_content, name='div_center_div_content'),
    url(regex=r'^div_center_div_footer/$', view=views.div_center_div_footer, name='div_center_div_footer'),
    #
    url(regex=r'^login/$', view=views.login, name='login'),
    url(regex=r'^login_forgot_credential_1/$', view=views.login_forgot_credential_1, name='login_forgot_credential_1'),
    url(regex=r'^login_forgot_credential_2/(?P<pk>\d+)/$', view=views.login_forgot_credential_2, name='login_forgot_credential_2'),
    url(regex=r'^login_forgot_credential_3/(?P<pk>\d+)/$', view=views.login_forgot_credential_3, name='login_forgot_credential_3'),
    url(regex=r'^login_request/$', view=views.login_request, name='login_request'),
    url(regex=r'^logout/$', view=views.logout, name='logout'),
    url(regex=r'^profile/$', view=views.profile, name='profile'),
    url(regex=r'^locale/$', view=views.locale, name='locale'),
    #
    url(r'^module/', include('src.home.module.urls', namespace='module')),
]

service_django/application/src/administration/module/security/group/views.py
# -*- coding: utf-8 -*-
from .... import utils as administration_utils
from .. import utils as administration_module_utils
from . import utils as administration_module_model_utils
from src.security import (
    decorators as security_decorators,
    utils as security_utils
)


@security_decorators.required_request_is_ajax()
def index(request):
    return administration_utils.jsonresponse_template_div_center_div_content(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', }
)
def table_tbody_and_pagination_reload(request):
    return administration_utils.jsonresponse_template_div_center_div_content_table_tbody_and_pagination_reload(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', 'security_group_update', }
)
def table_tbody_and_pagination_tree_reload(request):
    return administration_utils.jsonresponse_template_div_center_div_content_table_tbody_and_pagination_tree_reload(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', 'security_group_create', }
)
def create(request):
    return administration_utils.jsonresponse_template_div_modal_create(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', 'security_group_detail', }
)
def detail(request, pk):
    return administration_utils.jsonresponse_template_div_modal_detail(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', 'security_group_update', }
)
def update(request, pk):
    return administration_utils.jsonresponse_template_div_modal_update(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_group_list', 'security_group_delete', }
)
def delete(request, pk):
    return administration_utils.jsonresponse_template_div_modal_delete(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )

service_django/application/src/administration/module/security/ldapuser/views.py
# -*- coding: utf-8 -*-
from .... import utils as administration_utils
from .. import utils as administration_module_utils
from . import utils as administration_module_model_utils
from src.security import (
    decorators as security_decorators,
    utils as security_utils
)


@security_decorators.required_request_is_ajax()
def index(request):
    return administration_utils.jsonresponse_template_div_center_div_content(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_ldapuser_list', }
)
def table_tbody_and_pagination_reload(request):
    return administration_utils.jsonresponse_template_div_center_div_content_table_tbody_and_pagination_reload(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_ldapuser_list', 'security_ldapuser_create', }
)
def create(request):
    return administration_utils.jsonresponse_template_div_modal_create(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_ldapuser_list', 'security_ldapuser_detail', }
)
def detail(request, pk):
    return administration_utils.jsonresponse_template_div_modal_detail(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_ldapuser_list', 'security_ldapuser_update', }
)
def update(request, pk):
    return administration_utils.jsonresponse_template_div_modal_update(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_ldapuser_list', 'security_ldapuser_delete', }
)
def delete(request, pk):
    return administration_utils.jsonresponse_template_div_modal_delete(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )

service_django/application/src/administration/module/security/localuser/views.py
# -*- coding: utf-8 -*-
from .... import utils as administration_utils
from .. import utils as administration_module_utils
from . import utils as administration_module_model_utils
from src.security import (
    decorators as security_decorators,
    utils as security_utils
)


@security_decorators.required_request_is_ajax()
def index(request):
    return administration_utils.jsonresponse_template_div_center_div_content(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_localuser_list', }
)
def table_tbody_and_pagination_reload(request):
    return administration_utils.jsonresponse_template_div_center_div_content_table_tbody_and_pagination_reload(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_localuser_list', 'security_localuser_create', }
)
def create(request):
    return administration_utils.jsonresponse_template_div_modal_create(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_localuser_list', 'security_localuser_detail', }
)
def detail(request, pk):
    return administration_utils.jsonresponse_template_div_modal_detail(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_localuser_list', 'security_localuser_update', }
)
def update(request, pk):
    return administration_utils.jsonresponse_template_div_modal_update(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_localuser_list', 'security_localuser_delete', }
)
def delete(request, pk):
    return administration_utils.jsonresponse_template_div_modal_delete(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )

service_django/application/src/administration/module/security/permission/views.py
# -*- coding: utf-8 -*-
from .... import utils as administration_utils
from .. import utils as administration_module_utils
from . import utils as administration_module_model_utils
from src.security import (
    decorators as security_decorators,
    utils as security_utils
)


@security_decorators.required_request_is_ajax()
def index(request):
    return administration_utils.jsonresponse_template_div_center_div_content(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_permission_list', }
)
def table_tbody_and_pagination_reload(request):
    return administration_utils.jsonresponse_template_div_center_div_content_table_tbody_and_pagination_reload(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_permission_list', 'security_permission_detail', }
)
def detail(request, pk):
    return administration_utils.jsonresponse_template_div_modal_detail(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )


@security_decorators.required_request_is_ajax()
@security_decorators.required_security_user_has_permission(
    security_from_module=security_utils.SECURITY_FROM_MODULE_ADMINISTRATION,
    set_identifier___to_verify={'security_permission_list', 'security_permission_update', }
)
def update(request, pk):
    return administration_utils.jsonresponse_template_div_modal_update(
        request=request,
        utils_module=administration_module_utils,
        utils_module_model=administration_module_model_utils,
        pk=pk
    )

service_django/application/templates/home/_include_/div_modal/security/login.html
{% load i18n %}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header d-flex flex-row justify-content-between">
            <p class="modal-title align-self-center"><i class="fa fa-sign-in"></i> {% trans "SECURITY_LOGIN" %}</p>
            <button type="button" class="btn btn-sm btn-action btn-action-outline align-self-center link-div-modal-action-close" title="{% trans "SECURITY_ACTION_CLOSE" %}"><i class="fa fa-close"></i></button>
        </div>
        <div class="modal-body">
            <div class="modal-tab">
                <nav>
                    <div id="tabs" class="nav nav-tabs" role="tablist">
                        <a id="tab-ldap" class="nav-item nav-link {% if ctx_tab_ldapuserlogin %}active{% endif %} {% if ctx_form_ldapuserlogin.ldap_identifier.errors or ctx_form_ldapuserlogin.ldap_password.errors %}has-error{% endif %}" aria-selected="{% if ctx_tab_ldapuserlogin %}true{% else %}false{% endif %}" aria-controls="content-ldap" href="#content-ldap" data-toggle="tab" role="tab">{% trans "SECURITY_LOGIN_MODEL_LDAPUSER" %}</a>
                        <a id="tab-local" class="nav-item nav-link {% if ctx_tab_localuserlogin %}active{% endif %} {% if ctx_form_localuserlogin.local_identifier.errors or ctx_form_localuserlogin.local_password.errors %}has-error{% endif %}" aria-selected="{% if ctx_tab_localuserlogin %}true{% else %}false{% endif %}" aria-controls="content-local" href="#content-local" data-toggle="tab" role="tab">{% trans "SECURITY_LOGIN_MODEL_LOCALUSER" %}</a>
                    </div>
                </nav>
                <div id="contents" class="tab-content">
                    <div id="content-ldap" class="tab-pane fade {% if ctx_tab_ldapuserlogin %}show active{% endif %}" aria-labelledby="tab-ldap" role="tabpanel">
                        <form method="post" action="{% url "home:login" %}?tab_ldapuserlogin=True" class="link-div-modal-action-login">
                            {% csrf_token %}
                            <div class="tab-pane-modal-form">
                                <!-- Modal Menssage -->
                                <div class="modal-message"></div>
                                <!-- Modal Form -->
                                <div class="modal-form">
                                    {% with ctx_field=ctx_form_ldapuserlogin.ldap_identifier %}
                                        {% include "home/_include_/div_modal/_include_/form/textfield/textfield.html" %}
                                    {% endwith %}
                                    {% with ctx_field=ctx_form_ldapuserlogin.ldap_password %}
                                        {% include "home/_include_/div_modal/_include_/form/textfield/textfield.html" %}
                                    {% endwith %}
                                    <div class="divider-transparent"></div>
                                    <div><a class="btn btn-sm btn-link link-div-modal-modal-reload" data-url="{% url "home:login_forgot_credential_1" %}?tab_ldapuserlogin_forgot_credential=True"><i class="fa fa-question-circle"></i> {% trans "SECURITY_LOGIN_LINK_FORGOT_CREDENTIAL" %}</a></div>
                                    <div><a class="btn btn-sm btn-link link-div-modal-modal-reload" data-url="{% url "home:login_request" %}?tab_ldapuserlogin_request=True"><i class="fa fa-question-circle"></i> {% trans "SECURITY_LOGIN_LINK_REQUEST" %}</a></div>
                                </div>
                            </div>
                            <div class="modal-footer d-flex flex-row justify-content-between">
                                <div>
                                    <button type="submit" class="btn btn-sm btn-action btn-action-bg" title="{% trans "SECURITY_ACTION_LOGIN" %}">
                                        <i class="fa fa-sign-in"></i> {% trans "SECURITY_ACTION_LOGIN" %}
                                    </button>
                                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-action-refresh-from-security-login" data-url="{% url "home:login" %}?tab_ldapuserlogin=True" title="{% trans "SECURITY_ACTION_REFRESH" %}">
                                        <i class="fa fa-refresh"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_REFRESH" %}</span>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-action-close" title="{% trans "SECURITY_ACTION_CLOSE" %}">
                                        <i class="fa fa-close"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_CLOSE" %}</span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div id="content-local" class="tab-pane fade {% if ctx_tab_localuserlogin %}show active{% endif %}" aria-labelledby="tab-local" role="tabpanel">
                        <form method="post" action="{% url "home:login" %}?tab_localuserlogin=True" class="link-div-modal-action-login">
                            {% csrf_token %}
                            <div class="tab-pane-modal-form">
                                <!-- Modal Menssage -->
                                <div class="modal-message"></div>
                                <!-- Modal Form -->
                                <div class="modal-form">
                                    {% with ctx_field=ctx_form_localuserlogin.local_identifier %}
                                        {% include "home/_include_/div_modal/_include_/form/textfield/textfield.html" %}
                                    {% endwith %}
                                    {% with ctx_field=ctx_form_localuserlogin.local_password %}
                                        {% include "home/_include_/div_modal/_include_/form/textfield/textfield.html" %}
                                    {% endwith %}
                                    <div class="divider-transparent"></div>
                                    <div><a class="btn btn-sm btn-link link-div-modal-modal-reload" data-url="{% url "home:login_forgot_credential_1" %}?tab_localuserlogin_forgot_credential=True"><i class="fa fa-question-circle"></i> {% trans "SECURITY_LOGIN_LINK_FORGOT_CREDENTIAL" %}</a></div>
                                    {% comment %}<div><a class="btn btn-sm btn-link link-div-modal-modal-reload" data-url="{% url "home:login_request" %}?tab_localuserlogin_request=True"><i class="fa fa-question-circle"></i> {% trans "SECURITY_LOGIN_LINK_REQUEST" %}</a></div>{% endcomment %}
                                </div>
                            </div>
                            <div class="modal-footer d-flex flex-row justify-content-between">
                                <div>
                                    <button type="submit" class="btn btn-sm btn-action btn-action-bg" title="{% trans "SECURITY_ACTION_LOGIN" %}">
                                        <i class="fa fa-sign-in"></i> {% trans "SECURITY_ACTION_LOGIN" %}
                                    </button>
                                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-action-refresh-from-security-login" data-url="{% url "home:login" %}?tab_localuserlogin=True" title="{% trans "SECURITY_ACTION_REFRESH" %}">
                                        <i class="fa fa-refresh"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_REFRESH" %}</span>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-action-close" title="{% trans "SECURITY_ACTION_CLOSE" %}">
                                        <i class="fa fa-close"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_CLOSE" %}</span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

service_django/application/templates/home/_include_/div_modal/security/login_forgot_credential_1.html
{% load i18n %}

<div class="modal-dialog">
    <div class="modal-content">
        <form method="post" action="{% url "home:login_forgot_credential_1" %}{% if ctx_tab_localuserlogin_forgot_credential == True %}?tab_localuserlogin_forgot_credential=True{% else %}{% if ctx_tab_ldapuserlogin_forgot_credential == True %}?tab_ldapuserlogin_forgot_credential=True{% endif %}{% endif %}" class="link-div-modal-modal-action-submit-keep-div-modal">
            {% csrf_token %}
            <div class="modal-header d-flex flex-row justify-content-between">
                <p class="modal-title align-self-center"><i class="fa fa-user"></i> {% trans "SECURITY_LOGIN_FORGOT_CREDENTIAL" %} {% if ctx_tab_localuserlogin_forgot_credential == True %}&OpenCurlyDoubleQuote;{% trans "SECURITY_LOGIN_FORGOT_CREDENTIAL_LOCALUSER" %}&CloseCurlyDoubleQuote;{% else %}{% if ctx_tab_ldapuserlogin_forgot_credential == True %}&OpenCurlyDoubleQuote;{% trans "SECURITY_LOGIN_FORGOT_CREDENTIAL_LDAPUSER" %}&CloseCurlyDoubleQuote;{% endif %}{% endif %}</p>
                <button type="button" class="btn btn-sm btn-action btn-action-outline align-self-center link-div-modal-modal-action-close" title="{% trans "SECURITY_ACTION_CLOSE" %}"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <!-- Modal Menssage -->
                <div class="modal-message"></div>
                <!-- Modal Form Field -->
                <div class="modal-form">
                    {% with ctx_field=ctx_form.email %}
                        {% include "home/_include_/div_modal/_include_/form/textfield/textfield.html" %}
                    {% endwith %}
                </div>
            </div>
            <div class="modal-footer d-flex flex-row justify-content-between">
                <div>
                    <button type="submit" class="btn btn-sm btn-action btn-action-bg" title="{% trans "SECURITY_ACTION_SUBMIT" %}">
                        <i class="fa fa-send"></i> {% trans "SECURITY_ACTION_SUBMIT" %}
                    </button>
                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-modal-action-refresh" data-url="{% url "home:login_forgot_credential_1" %}{% if ctx_tab_localuserlogin_forgot_credential == True %}?tab_localuserlogin_forgot_credential=True{% else %}{% if ctx_tab_ldapuserlogin_forgot_credential == True %}?tab_ldapuserlogin_forgot_credential=True{% endif %}{% endif %}" title="{% trans "SECURITY_ACTION_REFRESH" %}">
                        <i class="fa fa-refresh"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_REFRESH" %}</span>
                    </button>
                    <button type="button" class="btn btn-sm btn-action btn-action-outline link-div-modal-modal-action-close" title="{% trans "SECURITY_ACTION_CLOSE" %}">
                        <i class="fa fa-close"></i> <span class="d-none d-md-inline-block">{% trans "SECURITY_ACTION_CLOSE" %}</span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>